// Generated by gencpp from file pkg_msg/status.msg
// DO NOT EDIT!


#ifndef PKG_MSG_MESSAGE_STATUS_H
#define PKG_MSG_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_msg
{
template <class ContainerAllocator>
struct status_
{
  typedef status_<ContainerAllocator> Type;

  status_()
    : temperature(0)
    , are_motors_up(false)
    , debug_message()  {
    }
  status_(const ContainerAllocator& _alloc)
    : temperature(0)
    , are_motors_up(false)
    , debug_message(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _are_motors_up_type;
  _are_motors_up_type are_motors_up;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _debug_message_type;
  _debug_message_type debug_message;





  typedef boost::shared_ptr< ::pkg_msg::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_msg::status_<ContainerAllocator> const> ConstPtr;

}; // struct status_

typedef ::pkg_msg::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::pkg_msg::status > statusPtr;
typedef boost::shared_ptr< ::pkg_msg::status const> statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_msg::status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_msg::status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_msg::status_<ContainerAllocator1> & lhs, const ::pkg_msg::status_<ContainerAllocator2> & rhs)
{
  return lhs.temperature == rhs.temperature &&
    lhs.are_motors_up == rhs.are_motors_up &&
    lhs.debug_message == rhs.debug_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_msg::status_<ContainerAllocator1> & lhs, const ::pkg_msg::status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pkg_msg::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_msg::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_msg::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_msg::status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_msg::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_msg::status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_msg::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78c14d0acfcb188b1e76c88d6e81f318";
  }

  static const char* value(const ::pkg_msg::status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78c14d0acfcb188bULL;
  static const uint64_t static_value2 = 0x1e76c88d6e81f318ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_msg::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_msg/status";
  }

  static const char* value(const ::pkg_msg::status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_msg::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 temperature\n"
"bool are_motors_up\n"
"string debug_message\n"
;
  }

  static const char* value(const ::pkg_msg::status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_msg::status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
      stream.next(m.are_motors_up);
      stream.next(m.debug_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_msg::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_msg::status_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    Printer<int64_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "are_motors_up: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.are_motors_up);
    s << indent << "debug_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.debug_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_MSG_MESSAGE_STATUS_H
