// Generated by gencpp from file battery_msgs/battery_status.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_BATTERY_STATUS_H
#define BATTERY_MSGS_MESSAGE_BATTERY_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_msgs
{
template <class ContainerAllocator>
struct battery_status_
{
  typedef battery_status_<ContainerAllocator> Type;

  battery_status_()
    : battery_percentage(0)
    , battery_state(0)  {
    }
  battery_status_(const ContainerAllocator& _alloc)
    : battery_percentage(0)
    , battery_state(0)  {
  (void)_alloc;
    }



   typedef int64_t _battery_percentage_type;
  _battery_percentage_type battery_percentage;

   typedef int64_t _battery_state_type;
  _battery_state_type battery_state;





  typedef boost::shared_ptr< ::battery_msgs::battery_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_msgs::battery_status_<ContainerAllocator> const> ConstPtr;

}; // struct battery_status_

typedef ::battery_msgs::battery_status_<std::allocator<void> > battery_status;

typedef boost::shared_ptr< ::battery_msgs::battery_status > battery_statusPtr;
typedef boost::shared_ptr< ::battery_msgs::battery_status const> battery_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_msgs::battery_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_msgs::battery_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::battery_msgs::battery_status_<ContainerAllocator1> & lhs, const ::battery_msgs::battery_status_<ContainerAllocator2> & rhs)
{
  return lhs.battery_percentage == rhs.battery_percentage &&
    lhs.battery_state == rhs.battery_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::battery_msgs::battery_status_<ContainerAllocator1> & lhs, const ::battery_msgs::battery_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace battery_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::battery_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::battery_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::battery_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::battery_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::battery_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::battery_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_msgs::battery_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "957b95659cace2f80a6937514c22929b";
  }

  static const char* value(const ::battery_msgs::battery_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x957b95659cace2f8ULL;
  static const uint64_t static_value2 = 0x0a6937514c22929bULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_msgs::battery_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_msgs/battery_status";
  }

  static const char* value(const ::battery_msgs::battery_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_msgs::battery_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 battery_percentage\n"
"int64 battery_state\n"
;
  }

  static const char* value(const ::battery_msgs::battery_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_msgs::battery_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.battery_percentage);
      stream.next(m.battery_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_msgs::battery_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_msgs::battery_status_<ContainerAllocator>& v)
  {
    s << indent << "battery_percentage: ";
    Printer<int64_t>::stream(s, indent + "  ", v.battery_percentage);
    s << indent << "battery_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.battery_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_BATTERY_STATUS_H
