// Generated by gencpp from file battery_msgs/button.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_BUTTON_H
#define BATTERY_MSGS_MESSAGE_BUTTON_H

#include <ros/service_traits.h>


#include <battery_msgs/buttonRequest.h>
#include <battery_msgs/buttonResponse.h>


namespace battery_msgs
{

struct button
{

typedef buttonRequest Request;
typedef buttonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct button
} // namespace battery_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::battery_msgs::button > {
  static const char* value()
  {
    return "d768bdedadf64cabd792cf13b0c9dcc6";
  }

  static const char* value(const ::battery_msgs::button&) { return value(); }
};

template<>
struct DataType< ::battery_msgs::button > {
  static const char* value()
  {
    return "battery_msgs/button";
  }

  static const char* value(const ::battery_msgs::button&) { return value(); }
};


// service_traits::MD5Sum< ::battery_msgs::buttonRequest> should match
// service_traits::MD5Sum< ::battery_msgs::button >
template<>
struct MD5Sum< ::battery_msgs::buttonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::battery_msgs::button >::value();
  }
  static const char* value(const ::battery_msgs::buttonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::battery_msgs::buttonRequest> should match
// service_traits::DataType< ::battery_msgs::button >
template<>
struct DataType< ::battery_msgs::buttonRequest>
{
  static const char* value()
  {
    return DataType< ::battery_msgs::button >::value();
  }
  static const char* value(const ::battery_msgs::buttonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::battery_msgs::buttonResponse> should match
// service_traits::MD5Sum< ::battery_msgs::button >
template<>
struct MD5Sum< ::battery_msgs::buttonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::battery_msgs::button >::value();
  }
  static const char* value(const ::battery_msgs::buttonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::battery_msgs::buttonResponse> should match
// service_traits::DataType< ::battery_msgs::button >
template<>
struct DataType< ::battery_msgs::buttonResponse>
{
  static const char* value()
  {
    return DataType< ::battery_msgs::button >::value();
  }
  static const char* value(const ::battery_msgs::buttonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_BUTTON_H
