// Generated by gencpp from file battery_msgs/buttonResponse.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_BUTTONRESPONSE_H
#define BATTERY_MSGS_MESSAGE_BUTTONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_msgs
{
template <class ContainerAllocator>
struct buttonResponse_
{
  typedef buttonResponse_<ContainerAllocator> Type;

  buttonResponse_()
    : power(0)  {
    }
  buttonResponse_(const ContainerAllocator& _alloc)
    : power(0)  {
  (void)_alloc;
    }



   typedef int64_t _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::battery_msgs::buttonResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_msgs::buttonResponse_<ContainerAllocator> const> ConstPtr;

}; // struct buttonResponse_

typedef ::battery_msgs::buttonResponse_<std::allocator<void> > buttonResponse;

typedef boost::shared_ptr< ::battery_msgs::buttonResponse > buttonResponsePtr;
typedef boost::shared_ptr< ::battery_msgs::buttonResponse const> buttonResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_msgs::buttonResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_msgs::buttonResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::battery_msgs::buttonResponse_<ContainerAllocator1> & lhs, const ::battery_msgs::buttonResponse_<ContainerAllocator2> & rhs)
{
  return lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::battery_msgs::buttonResponse_<ContainerAllocator1> & lhs, const ::battery_msgs::buttonResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace battery_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::buttonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::buttonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::buttonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::buttonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::buttonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::buttonResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_msgs::buttonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c99d52463144470019284766865250e0";
  }

  static const char* value(const ::battery_msgs::buttonResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc99d524631444700ULL;
  static const uint64_t static_value2 = 0x19284766865250e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_msgs::buttonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_msgs/buttonResponse";
  }

  static const char* value(const ::battery_msgs::buttonResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_msgs::buttonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 power\n"
"\n"
;
  }

  static const char* value(const ::battery_msgs::buttonResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_msgs::buttonResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct buttonResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_msgs::buttonResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_msgs::buttonResponse_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<int64_t>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_BUTTONRESPONSE_H
