// Generated by gencpp from file battery_msgs/buttonRequest.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_BUTTONREQUEST_H
#define BATTERY_MSGS_MESSAGE_BUTTONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_msgs
{
template <class ContainerAllocator>
struct buttonRequest_
{
  typedef buttonRequest_<ContainerAllocator> Type;

  buttonRequest_()
    : on(0)  {
    }
  buttonRequest_(const ContainerAllocator& _alloc)
    : on(0)  {
  (void)_alloc;
    }



   typedef int64_t _on_type;
  _on_type on;





  typedef boost::shared_ptr< ::battery_msgs::buttonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_msgs::buttonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct buttonRequest_

typedef ::battery_msgs::buttonRequest_<std::allocator<void> > buttonRequest;

typedef boost::shared_ptr< ::battery_msgs::buttonRequest > buttonRequestPtr;
typedef boost::shared_ptr< ::battery_msgs::buttonRequest const> buttonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_msgs::buttonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_msgs::buttonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::battery_msgs::buttonRequest_<ContainerAllocator1> & lhs, const ::battery_msgs::buttonRequest_<ContainerAllocator2> & rhs)
{
  return lhs.on == rhs.on;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::battery_msgs::buttonRequest_<ContainerAllocator1> & lhs, const ::battery_msgs::buttonRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace battery_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::buttonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::buttonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::buttonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::buttonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::buttonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::buttonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_msgs::buttonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b526c44c241904733faa3b670847c982";
  }

  static const char* value(const ::battery_msgs::buttonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb526c44c24190473ULL;
  static const uint64_t static_value2 = 0x3faa3b670847c982ULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_msgs::buttonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_msgs/buttonRequest";
  }

  static const char* value(const ::battery_msgs::buttonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_msgs::buttonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 on\n"
;
  }

  static const char* value(const ::battery_msgs::buttonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_msgs::buttonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct buttonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_msgs::buttonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_msgs::buttonRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<int64_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_BUTTONREQUEST_H
