// Generated by gencpp from file battery_msgs/compute_battery.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_COMPUTE_BATTERY_H
#define BATTERY_MSGS_MESSAGE_COMPUTE_BATTERY_H

#include <ros/service_traits.h>


#include <battery_msgs/compute_batteryRequest.h>
#include <battery_msgs/compute_batteryResponse.h>


namespace battery_msgs
{

struct compute_battery
{

typedef compute_batteryRequest Request;
typedef compute_batteryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct compute_battery
} // namespace battery_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::battery_msgs::compute_battery > {
  static const char* value()
  {
    return "0a0786e9c7f1dae93c6b1b4c8555c6e5";
  }

  static const char* value(const ::battery_msgs::compute_battery&) { return value(); }
};

template<>
struct DataType< ::battery_msgs::compute_battery > {
  static const char* value()
  {
    return "battery_msgs/compute_battery";
  }

  static const char* value(const ::battery_msgs::compute_battery&) { return value(); }
};


// service_traits::MD5Sum< ::battery_msgs::compute_batteryRequest> should match
// service_traits::MD5Sum< ::battery_msgs::compute_battery >
template<>
struct MD5Sum< ::battery_msgs::compute_batteryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::battery_msgs::compute_battery >::value();
  }
  static const char* value(const ::battery_msgs::compute_batteryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::battery_msgs::compute_batteryRequest> should match
// service_traits::DataType< ::battery_msgs::compute_battery >
template<>
struct DataType< ::battery_msgs::compute_batteryRequest>
{
  static const char* value()
  {
    return DataType< ::battery_msgs::compute_battery >::value();
  }
  static const char* value(const ::battery_msgs::compute_batteryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::battery_msgs::compute_batteryResponse> should match
// service_traits::MD5Sum< ::battery_msgs::compute_battery >
template<>
struct MD5Sum< ::battery_msgs::compute_batteryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::battery_msgs::compute_battery >::value();
  }
  static const char* value(const ::battery_msgs::compute_batteryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::battery_msgs::compute_batteryResponse> should match
// service_traits::DataType< ::battery_msgs::compute_battery >
template<>
struct DataType< ::battery_msgs::compute_batteryResponse>
{
  static const char* value()
  {
    return DataType< ::battery_msgs::compute_battery >::value();
  }
  static const char* value(const ::battery_msgs::compute_batteryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_COMPUTE_BATTERY_H
