// Generated by gencpp from file battery_msgs/compute_batteryRequest.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_COMPUTE_BATTERYREQUEST_H
#define BATTERY_MSGS_MESSAGE_COMPUTE_BATTERYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_msgs
{
template <class ContainerAllocator>
struct compute_batteryRequest_
{
  typedef compute_batteryRequest_<ContainerAllocator> Type;

  compute_batteryRequest_()
    : percentage(0)  {
    }
  compute_batteryRequest_(const ContainerAllocator& _alloc)
    : percentage(0)  {
  (void)_alloc;
    }



   typedef int64_t _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct compute_batteryRequest_

typedef ::battery_msgs::compute_batteryRequest_<std::allocator<void> > compute_batteryRequest;

typedef boost::shared_ptr< ::battery_msgs::compute_batteryRequest > compute_batteryRequestPtr;
typedef boost::shared_ptr< ::battery_msgs::compute_batteryRequest const> compute_batteryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_msgs::compute_batteryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::battery_msgs::compute_batteryRequest_<ContainerAllocator1> & lhs, const ::battery_msgs::compute_batteryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::battery_msgs::compute_batteryRequest_<ContainerAllocator1> & lhs, const ::battery_msgs::compute_batteryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace battery_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face31f38d20abbde445df7aa912bb07";
  }

  static const char* value(const ::battery_msgs::compute_batteryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xface31f38d20abbdULL;
  static const uint64_t static_value2 = 0xe445df7aa912bb07ULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_msgs/compute_batteryRequest";
  }

  static const char* value(const ::battery_msgs::compute_batteryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 percentage\n"
;
  }

  static const char* value(const ::battery_msgs::compute_batteryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct compute_batteryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_msgs::compute_batteryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_msgs::compute_batteryRequest_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<int64_t>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_COMPUTE_BATTERYREQUEST_H
