// Generated by gencpp from file my_robot_msgs/action_csFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_ACTION_CSFEEDBACK_H
#define MY_ROBOT_MSGS_MESSAGE_ACTION_CSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct action_csFeedback_
{
  typedef action_csFeedback_<ContainerAllocator> Type;

  action_csFeedback_()
    : per(0.0)  {
    }
  action_csFeedback_(const ContainerAllocator& _alloc)
    : per(0.0)  {
  (void)_alloc;
    }



   typedef double _per_type;
  _per_type per;





  typedef boost::shared_ptr< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct action_csFeedback_

typedef ::my_robot_msgs::action_csFeedback_<std::allocator<void> > action_csFeedback;

typedef boost::shared_ptr< ::my_robot_msgs::action_csFeedback > action_csFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_msgs::action_csFeedback const> action_csFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::action_csFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::action_csFeedback_<ContainerAllocator1> & lhs, const ::my_robot_msgs::action_csFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.per == rhs.per;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::action_csFeedback_<ContainerAllocator1> & lhs, const ::my_robot_msgs::action_csFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7e488982e55113a6a4ffa6d57909452";
  }

  static const char* value(const ::my_robot_msgs::action_csFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7e488982e55113aULL;
  static const uint64_t static_value2 = 0x6a4ffa6d57909452ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/action_csFeedback";
  }

  static const char* value(const ::my_robot_msgs::action_csFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 per                                   \n"
"\n"
;
  }

  static const char* value(const ::my_robot_msgs::action_csFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.per);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct action_csFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::action_csFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::action_csFeedback_<ContainerAllocator>& v)
  {
    s << indent << "per: ";
    Printer<double>::stream(s, indent + "  ", v.per);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_ACTION_CSFEEDBACK_H
