// Generated by gencpp from file my_robot_msgs/num_actionGoal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONGOAL_H
#define MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct num_actionGoal_
{
  typedef num_actionGoal_<ContainerAllocator> Type;

  num_actionGoal_()
    : bin_num(0)  {
    }
  num_actionGoal_(const ContainerAllocator& _alloc)
    : bin_num(0)  {
  (void)_alloc;
    }



   typedef int64_t _bin_num_type;
  _bin_num_type bin_num;





  typedef boost::shared_ptr< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct num_actionGoal_

typedef ::my_robot_msgs::num_actionGoal_<std::allocator<void> > num_actionGoal;

typedef boost::shared_ptr< ::my_robot_msgs::num_actionGoal > num_actionGoalPtr;
typedef boost::shared_ptr< ::my_robot_msgs::num_actionGoal const> num_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::num_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::num_actionGoal_<ContainerAllocator1> & lhs, const ::my_robot_msgs::num_actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.bin_num == rhs.bin_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::num_actionGoal_<ContainerAllocator1> & lhs, const ::my_robot_msgs::num_actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1327ba78bb595c490506018fc2008a3e";
  }

  static const char* value(const ::my_robot_msgs::num_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1327ba78bb595c49ULL;
  static const uint64_t static_value2 = 0x0506018fc2008a3eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/num_actionGoal";
  }

  static const char* value(const ::my_robot_msgs::num_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"int64 bin_num\n"
;
  }

  static const char* value(const ::my_robot_msgs::num_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bin_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::num_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::num_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "bin_num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.bin_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONGOAL_H
