// Generated by gencpp from file my_robot_msgs/num_actionResult.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONRESULT_H
#define MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct num_actionResult_
{
  typedef num_actionResult_<ContainerAllocator> Type;

  num_actionResult_()
    : number()  {
    }
  num_actionResult_(const ContainerAllocator& _alloc)
    : number(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::my_robot_msgs::num_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::num_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct num_actionResult_

typedef ::my_robot_msgs::num_actionResult_<std::allocator<void> > num_actionResult;

typedef boost::shared_ptr< ::my_robot_msgs::num_actionResult > num_actionResultPtr;
typedef boost::shared_ptr< ::my_robot_msgs::num_actionResult const> num_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::num_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::num_actionResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::num_actionResult_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::num_actionResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::num_actionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::num_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::num_actionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::num_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1390643684d42806cde16cb777d15235";
  }

  static const char* value(const ::my_robot_msgs::num_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1390643684d42806ULL;
  static const uint64_t static_value2 = 0xcde16cb777d15235ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/num_actionResult";
  }

  static const char* value(const ::my_robot_msgs::num_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"string number\n"
;
  }

  static const char* value(const ::my_robot_msgs::num_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::num_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::num_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONRESULT_H
