// Generated by gencpp from file my_robot_msgs/num_srv.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_NUM_SRV_H
#define MY_ROBOT_MSGS_MESSAGE_NUM_SRV_H

#include <ros/service_traits.h>


#include <my_robot_msgs/num_srvRequest.h>
#include <my_robot_msgs/num_srvResponse.h>


namespace my_robot_msgs
{

struct num_srv
{

typedef num_srvRequest Request;
typedef num_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct num_srv
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::num_srv > {
  static const char* value()
  {
    return "fa0a9a2a723d413abaf66f55c0bec788";
  }

  static const char* value(const ::my_robot_msgs::num_srv&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::num_srv > {
  static const char* value()
  {
    return "my_robot_msgs/num_srv";
  }

  static const char* value(const ::my_robot_msgs::num_srv&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::num_srvRequest> should match
// service_traits::MD5Sum< ::my_robot_msgs::num_srv >
template<>
struct MD5Sum< ::my_robot_msgs::num_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::num_srv >::value();
  }
  static const char* value(const ::my_robot_msgs::num_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::num_srvRequest> should match
// service_traits::DataType< ::my_robot_msgs::num_srv >
template<>
struct DataType< ::my_robot_msgs::num_srvRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::num_srv >::value();
  }
  static const char* value(const ::my_robot_msgs::num_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::num_srvResponse> should match
// service_traits::MD5Sum< ::my_robot_msgs::num_srv >
template<>
struct MD5Sum< ::my_robot_msgs::num_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::num_srv >::value();
  }
  static const char* value(const ::my_robot_msgs::num_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::num_srvResponse> should match
// service_traits::DataType< ::my_robot_msgs::num_srv >
template<>
struct DataType< ::my_robot_msgs::num_srvResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::num_srv >::value();
  }
  static const char* value(const ::my_robot_msgs::num_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_NUM_SRV_H
