// Generated by gencpp from file my_robot_msgs/num_actionFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONFEEDBACK_H
#define MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct num_actionFeedback_
{
  typedef num_actionFeedback_<ContainerAllocator> Type;

  num_actionFeedback_()
    : percentage_done(0.0)  {
    }
  num_actionFeedback_(const ContainerAllocator& _alloc)
    : percentage_done(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_done_type;
  _percentage_done_type percentage_done;





  typedef boost::shared_ptr< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct num_actionFeedback_

typedef ::my_robot_msgs::num_actionFeedback_<std::allocator<void> > num_actionFeedback;

typedef boost::shared_ptr< ::my_robot_msgs::num_actionFeedback > num_actionFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_msgs::num_actionFeedback const> num_actionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator1> & lhs, const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage_done == rhs.percentage_done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator1> & lhs, const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4296ebcdecd59873bb1d94db9895591";
  }

  static const char* value(const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4296ebcdecd5987ULL;
  static const uint64_t static_value2 = 0x3bb1d94db9895591ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/num_actionFeedback";
  }

  static const char* value(const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 percentage_done\n"
"\n"
;
  }

  static const char* value(const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage_done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_actionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::num_actionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::num_actionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage_done: ";
    Printer<double>::stream(s, indent + "  ", v.percentage_done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_NUM_ACTIONFEEDBACK_H
