// Generated by gencpp from file my_robot_msgs/number.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_NUMBER_H
#define MY_ROBOT_MSGS_MESSAGE_NUMBER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct number_
{
  typedef number_<ContainerAllocator> Type;

  number_()
    : num(0)
    , str()  {
    }
  number_(const ContainerAllocator& _alloc)
    : num(0)
    , str(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::my_robot_msgs::number_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::number_<ContainerAllocator> const> ConstPtr;

}; // struct number_

typedef ::my_robot_msgs::number_<std::allocator<void> > number;

typedef boost::shared_ptr< ::my_robot_msgs::number > numberPtr;
typedef boost::shared_ptr< ::my_robot_msgs::number const> numberConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::number_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::number_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::number_<ContainerAllocator1> & lhs, const ::my_robot_msgs::number_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::number_<ContainerAllocator1> & lhs, const ::my_robot_msgs::number_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::number_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::number_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::number_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::number_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::number_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::number_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "192d0f9e8b86b0e07038f7c0d2ecb6b9";
  }

  static const char* value(const ::my_robot_msgs::number_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x192d0f9e8b86b0e0ULL;
  static const uint64_t static_value2 = 0x7038f7c0d2ecb6b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/number";
  }

  static const char* value(const ::my_robot_msgs::number_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::number_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
"string str\n"
;
  }

  static const char* value(const ::my_robot_msgs::number_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::number_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct number_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::number_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::number_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_NUMBER_H
