// Generated by gencpp from file my_robot_msgs/sig.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SIG_H
#define MY_ROBOT_MSGS_MESSAGE_SIG_H

#include <ros/service_traits.h>


#include <my_robot_msgs/sigRequest.h>
#include <my_robot_msgs/sigResponse.h>


namespace my_robot_msgs
{

struct sig
{

typedef sigRequest Request;
typedef sigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sig
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::sig > {
  static const char* value()
  {
    return "7bc8af7403a190711a182edad0f2139d";
  }

  static const char* value(const ::my_robot_msgs::sig&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::sig > {
  static const char* value()
  {
    return "my_robot_msgs/sig";
  }

  static const char* value(const ::my_robot_msgs::sig&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::sigRequest> should match
// service_traits::MD5Sum< ::my_robot_msgs::sig >
template<>
struct MD5Sum< ::my_robot_msgs::sigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::sig >::value();
  }
  static const char* value(const ::my_robot_msgs::sigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::sigRequest> should match
// service_traits::DataType< ::my_robot_msgs::sig >
template<>
struct DataType< ::my_robot_msgs::sigRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::sig >::value();
  }
  static const char* value(const ::my_robot_msgs::sigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::sigResponse> should match
// service_traits::MD5Sum< ::my_robot_msgs::sig >
template<>
struct MD5Sum< ::my_robot_msgs::sigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::sig >::value();
  }
  static const char* value(const ::my_robot_msgs::sigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::sigResponse> should match
// service_traits::DataType< ::my_robot_msgs::sig >
template<>
struct DataType< ::my_robot_msgs::sigResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::sig >::value();
  }
  static const char* value(const ::my_robot_msgs::sigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SIG_H
