// Generated by gencpp from file my_robot_msgs/signal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SIGNAL_H
#define MY_ROBOT_MSGS_MESSAGE_SIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct signal_
{
  typedef signal_<ContainerAllocator> Type;

  signal_()
    : signal_color()
    , signal_number(0)  {
    }
  signal_(const ContainerAllocator& _alloc)
    : signal_color(_alloc)
    , signal_number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _signal_color_type;
  _signal_color_type signal_color;

   typedef int64_t _signal_number_type;
  _signal_number_type signal_number;





  typedef boost::shared_ptr< ::my_robot_msgs::signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::signal_<ContainerAllocator> const> ConstPtr;

}; // struct signal_

typedef ::my_robot_msgs::signal_<std::allocator<void> > signal;

typedef boost::shared_ptr< ::my_robot_msgs::signal > signalPtr;
typedef boost::shared_ptr< ::my_robot_msgs::signal const> signalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::signal_<ContainerAllocator1> & lhs, const ::my_robot_msgs::signal_<ContainerAllocator2> & rhs)
{
  return lhs.signal_color == rhs.signal_color &&
    lhs.signal_number == rhs.signal_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::signal_<ContainerAllocator1> & lhs, const ::my_robot_msgs::signal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::signal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b51f0318452418723219cbc46255f5c";
  }

  static const char* value(const ::my_robot_msgs::signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b51f03184524187ULL;
  static const uint64_t static_value2 = 0x23219cbc46255f5cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/signal";
  }

  static const char* value(const ::my_robot_msgs::signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string signal_color\n"
"int64 signal_number\n"
;
  }

  static const char* value(const ::my_robot_msgs::signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal_color);
      stream.next(m.signal_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::signal_<ContainerAllocator>& v)
  {
    s << indent << "signal_color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.signal_color);
    s << indent << "signal_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.signal_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SIGNAL_H
