// Generated by gencpp from file my_robot_msgs/sigResponse.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SIGRESPONSE_H
#define MY_ROBOT_MSGS_MESSAGE_SIGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct sigResponse_
{
  typedef sigResponse_<ContainerAllocator> Type;

  sigResponse_()
    : signal_color()
    , message()  {
    }
  sigResponse_(const ContainerAllocator& _alloc)
    : signal_color(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _signal_color_type;
  _signal_color_type signal_color;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::my_robot_msgs::sigResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::sigResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sigResponse_

typedef ::my_robot_msgs::sigResponse_<std::allocator<void> > sigResponse;

typedef boost::shared_ptr< ::my_robot_msgs::sigResponse > sigResponsePtr;
typedef boost::shared_ptr< ::my_robot_msgs::sigResponse const> sigResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::sigResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::sigResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::sigResponse_<ContainerAllocator1> & lhs, const ::my_robot_msgs::sigResponse_<ContainerAllocator2> & rhs)
{
  return lhs.signal_color == rhs.signal_color &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::sigResponse_<ContainerAllocator1> & lhs, const ::my_robot_msgs::sigResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::sigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::sigResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::sigResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "450e30f7eff114429485a22ce41504da";
  }

  static const char* value(const ::my_robot_msgs::sigResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x450e30f7eff11442ULL;
  static const uint64_t static_value2 = 0x9485a22ce41504daULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/sigResponse";
  }

  static const char* value(const ::my_robot_msgs::sigResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string signal_color\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::my_robot_msgs::sigResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal_color);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sigResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::sigResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::sigResponse_<ContainerAllocator>& v)
  {
    s << indent << "signal_color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.signal_color);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SIGRESPONSE_H
