(cl:defpackage my_robot_msgs-msg
  (:use )
  (:export
   "<SIGNAL>"
   "SIGNAL"
   "<SIMPLE_SIGNALACTION>"
   "SIMPLE_SIGNALACTION"
   "<SIMPLE_SIGNALACTIONFEEDBACK>"
   "SIMPLE_SIGNALACTIONFEEDBACK"
   "<SIMPLE_SIGNALACTIONGOAL>"
   "SIMPLE_SIGNALACTIONGOAL"
   "<SIMPLE_SIGNALACTIONRESULT>"
   "SIMPLE_SIGNALACTIONRESULT"
   "<SIMPLE_SIGNALFEEDBACK>"
   "SIMPLE_SIGNALFEEDBACK"
   "<SIMPLE_SIGNALGOAL>"
   "SIMPLE_SIGNALGOAL"
   "<SIMPLE_SIGNALRESULT>"
   "SIMPLE_SIGNALRESULT"
  ))

