(cl:defpackage my_robot_msgs-msg
  (:use )
  (:export
   "<NUM_ACTIONACTION>"
   "NUM_ACTIONACTION"
   "<NUM_ACTIONACTIONFEEDBACK>"
   "NUM_ACTIONACTIONFEEDBACK"
   "<NUM_ACTIONACTIONGOAL>"
   "NUM_ACTIONACTIONGOAL"
   "<NUM_ACTIONACTIONRESULT>"
   "NUM_ACTIONACTIONRESULT"
   "<NUM_ACTIONFEEDBACK>"
   "NUM_ACTIONFEEDBACK"
   "<NUM_ACTIONGOAL>"
   "NUM_ACTIONGOAL"
   "<NUM_ACTIONRESULT>"
   "NUM_ACTIONRESULT"
   "<NUMBER>"
   "NUMBER"
  ))

