; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude action_csFeedback.msg.html

(cl:defclass <action_csFeedback> (roslisp-msg-protocol:ros-message)
  ((per
    :reader per
    :initarg :per
    :type cl:float
    :initform 0.0))
)

(cl:defclass action_csFeedback (<action_csFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <action_csFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'action_csFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<action_csFeedback> is deprecated: use my_robot_msgs-msg:action_csFeedback instead.")))

(cl:ensure-generic-function 'per-val :lambda-list '(m))
(cl:defmethod per-val ((m <action_csFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:per-val is deprecated.  Use my_robot_msgs-msg:per instead.")
  (per m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <action_csFeedback>) ostream)
  "Serializes a message object of type '<action_csFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'per))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <action_csFeedback>) istream)
  "Deserializes a message object of type '<action_csFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'per) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<action_csFeedback>)))
  "Returns string type for a message object of type '<action_csFeedback>"
  "my_robot_msgs/action_csFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'action_csFeedback)))
  "Returns string type for a message object of type 'action_csFeedback"
  "my_robot_msgs/action_csFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<action_csFeedback>)))
  "Returns md5sum for a message object of type '<action_csFeedback>"
  "c7e488982e55113a6a4ffa6d57909452")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'action_csFeedback)))
  "Returns md5sum for a message object of type 'action_csFeedback"
  "c7e488982e55113a6a4ffa6d57909452")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<action_csFeedback>)))
  "Returns full string definition for message of type '<action_csFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 per                                   ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'action_csFeedback)))
  "Returns full string definition for message of type 'action_csFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 per                                   ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <action_csFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <action_csFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'action_csFeedback
    (cl:cons ':per (per msg))
))
