; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude num_actionFeedback.msg.html

(cl:defclass <num_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage_done
    :reader percentage_done
    :initarg :percentage_done
    :type cl:float
    :initform 0.0))
)

(cl:defclass num_actionFeedback (<num_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <num_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'num_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<num_actionFeedback> is deprecated: use my_robot_msgs-msg:num_actionFeedback instead.")))

(cl:ensure-generic-function 'percentage_done-val :lambda-list '(m))
(cl:defmethod percentage_done-val ((m <num_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:percentage_done-val is deprecated.  Use my_robot_msgs-msg:percentage_done instead.")
  (percentage_done m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <num_actionFeedback>) ostream)
  "Serializes a message object of type '<num_actionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percentage_done))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <num_actionFeedback>) istream)
  "Deserializes a message object of type '<num_actionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage_done) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<num_actionFeedback>)))
  "Returns string type for a message object of type '<num_actionFeedback>"
  "my_robot_msgs/num_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'num_actionFeedback)))
  "Returns string type for a message object of type 'num_actionFeedback"
  "my_robot_msgs/num_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<num_actionFeedback>)))
  "Returns md5sum for a message object of type '<num_actionFeedback>"
  "e4296ebcdecd59873bb1d94db9895591")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'num_actionFeedback)))
  "Returns md5sum for a message object of type 'num_actionFeedback"
  "e4296ebcdecd59873bb1d94db9895591")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<num_actionFeedback>)))
  "Returns full string definition for message of type '<num_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage_done~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'num_actionFeedback)))
  "Returns full string definition for message of type 'num_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage_done~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <num_actionFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <num_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'num_actionFeedback
    (cl:cons ':percentage_done (percentage_done msg))
))
