; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude num_actionResult.msg.html

(cl:defclass <num_actionResult> (roslisp-msg-protocol:ros-message)
  ((number
    :reader number
    :initarg :number
    :type cl:string
    :initform ""))
)

(cl:defclass num_actionResult (<num_actionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <num_actionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'num_actionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<num_actionResult> is deprecated: use my_robot_msgs-msg:num_actionResult instead.")))

(cl:ensure-generic-function 'number-val :lambda-list '(m))
(cl:defmethod number-val ((m <num_actionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:number-val is deprecated.  Use my_robot_msgs-msg:number instead.")
  (number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <num_actionResult>) ostream)
  "Serializes a message object of type '<num_actionResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'number))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'number))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <num_actionResult>) istream)
  "Deserializes a message object of type '<num_actionResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'number) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'number) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<num_actionResult>)))
  "Returns string type for a message object of type '<num_actionResult>"
  "my_robot_msgs/num_actionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'num_actionResult)))
  "Returns string type for a message object of type 'num_actionResult"
  "my_robot_msgs/num_actionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<num_actionResult>)))
  "Returns md5sum for a message object of type '<num_actionResult>"
  "1390643684d42806cde16cb777d15235")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'num_actionResult)))
  "Returns md5sum for a message object of type 'num_actionResult"
  "1390643684d42806cde16cb777d15235")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<num_actionResult>)))
  "Returns full string definition for message of type '<num_actionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'num_actionResult)))
  "Returns full string definition for message of type 'num_actionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <num_actionResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'number))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <num_actionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'num_actionResult
    (cl:cons ':number (number msg))
))
