; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude num_actionGoal.msg.html

(cl:defclass <num_actionGoal> (roslisp-msg-protocol:ros-message)
  ((bin_num
    :reader bin_num
    :initarg :bin_num
    :type cl:integer
    :initform 0))
)

(cl:defclass num_actionGoal (<num_actionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <num_actionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'num_actionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<num_actionGoal> is deprecated: use my_robot_msgs-msg:num_actionGoal instead.")))

(cl:ensure-generic-function 'bin_num-val :lambda-list '(m))
(cl:defmethod bin_num-val ((m <num_actionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:bin_num-val is deprecated.  Use my_robot_msgs-msg:bin_num instead.")
  (bin_num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <num_actionGoal>) ostream)
  "Serializes a message object of type '<num_actionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'bin_num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <num_actionGoal>) istream)
  "Deserializes a message object of type '<num_actionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'bin_num) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<num_actionGoal>)))
  "Returns string type for a message object of type '<num_actionGoal>"
  "my_robot_msgs/num_actionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'num_actionGoal)))
  "Returns string type for a message object of type 'num_actionGoal"
  "my_robot_msgs/num_actionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<num_actionGoal>)))
  "Returns md5sum for a message object of type '<num_actionGoal>"
  "1327ba78bb595c490506018fc2008a3e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'num_actionGoal)))
  "Returns md5sum for a message object of type 'num_actionGoal"
  "1327ba78bb595c490506018fc2008a3e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<num_actionGoal>)))
  "Returns full string definition for message of type '<num_actionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int64 bin_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'num_actionGoal)))
  "Returns full string definition for message of type 'num_actionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int64 bin_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <num_actionGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <num_actionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'num_actionGoal
    (cl:cons ':bin_num (bin_num msg))
))
