(cl:defpackage my_robot_msgs-msg
  (:use )
  (:export
   "<ROBOT>"
   "ROBOT"
   "<SIMPLE_ACTIONACTION>"
   "SIMPLE_ACTIONACTION"
   "<SIMPLE_ACTIONACTIONFEEDBACK>"
   "SIMPLE_ACTIONACTIONFEEDBACK"
   "<SIMPLE_ACTIONACTIONGOAL>"
   "SIMPLE_ACTIONACTIONGOAL"
   "<SIMPLE_ACTIONACTIONRESULT>"
   "SIMPLE_ACTIONACTIONRESULT"
   "<SIMPLE_ACTIONFEEDBACK>"
   "SIMPLE_ACTIONFEEDBACK"
   "<SIMPLE_ACTIONGOAL>"
   "SIMPLE_ACTIONGOAL"
   "<SIMPLE_ACTIONRESULT>"
   "SIMPLE_ACTIONRESULT"
  ))

