; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude simple_actionFeedback.msg.html

(cl:defclass <simple_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass simple_actionFeedback (<simple_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <simple_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'simple_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<simple_actionFeedback> is deprecated: use my_robot_msgs-msg:simple_actionFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <simple_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:percentage-val is deprecated.  Use my_robot_msgs-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <simple_actionFeedback>) ostream)
  "Serializes a message object of type '<simple_actionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <simple_actionFeedback>) istream)
  "Deserializes a message object of type '<simple_actionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<simple_actionFeedback>)))
  "Returns string type for a message object of type '<simple_actionFeedback>"
  "my_robot_msgs/simple_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'simple_actionFeedback)))
  "Returns string type for a message object of type 'simple_actionFeedback"
  "my_robot_msgs/simple_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<simple_actionFeedback>)))
  "Returns md5sum for a message object of type '<simple_actionFeedback>"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'simple_actionFeedback)))
  "Returns md5sum for a message object of type 'simple_actionFeedback"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<simple_actionFeedback>)))
  "Returns full string definition for message of type '<simple_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'simple_actionFeedback)))
  "Returns full string definition for message of type 'simple_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <simple_actionFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <simple_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'simple_actionFeedback
    (cl:cons ':percentage (percentage msg))
))
