; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude moveFeedback.msg.html

(cl:defclass <moveFeedback> (roslisp-msg-protocol:ros-message)
  ((current_position
    :reader current_position
    :initarg :current_position
    :type cl:float
    :initform 0.0))
)

(cl:defclass moveFeedback (<moveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<moveFeedback> is deprecated: use my_robot_msgs-msg:moveFeedback instead.")))

(cl:ensure-generic-function 'current_position-val :lambda-list '(m))
(cl:defmethod current_position-val ((m <moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:current_position-val is deprecated.  Use my_robot_msgs-msg:current_position instead.")
  (current_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveFeedback>) ostream)
  "Serializes a message object of type '<moveFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'current_position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveFeedback>) istream)
  "Deserializes a message object of type '<moveFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_position) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveFeedback>)))
  "Returns string type for a message object of type '<moveFeedback>"
  "my_robot_msgs/moveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveFeedback)))
  "Returns string type for a message object of type 'moveFeedback"
  "my_robot_msgs/moveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveFeedback>)))
  "Returns md5sum for a message object of type '<moveFeedback>"
  "ec33e2052d46d95cbf67ffb2e2a5f076")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveFeedback)))
  "Returns md5sum for a message object of type 'moveFeedback"
  "ec33e2052d46d95cbf67ffb2e2a5f076")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveFeedback>)))
  "Returns full string definition for message of type '<moveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 current_position~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveFeedback)))
  "Returns full string definition for message of type 'moveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 current_position~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'moveFeedback
    (cl:cons ':current_position (current_position msg))
))
