// Generated by gencpp from file my_msgs/SetLedRequest.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_SETLEDREQUEST_H
#define MY_MSGS_MESSAGE_SETLEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct SetLedRequest_
{
  typedef SetLedRequest_<ContainerAllocator> Type;

  SetLedRequest_()
    : lednum(0)
    , state(false)  {
    }
  SetLedRequest_(const ContainerAllocator& _alloc)
    : lednum(0)
    , state(false)  {
  (void)_alloc;
    }



   typedef int64_t _lednum_type;
  _lednum_type lednum;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::my_msgs::SetLedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::SetLedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedRequest_

typedef ::my_msgs::SetLedRequest_<std::allocator<void> > SetLedRequest;

typedef boost::shared_ptr< ::my_msgs::SetLedRequest > SetLedRequestPtr;
typedef boost::shared_ptr< ::my_msgs::SetLedRequest const> SetLedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::SetLedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::SetLedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msgs::SetLedRequest_<ContainerAllocator1> & lhs, const ::my_msgs::SetLedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lednum == rhs.lednum &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msgs::SetLedRequest_<ContainerAllocator1> & lhs, const ::my_msgs::SetLedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_msgs::SetLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::SetLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::SetLedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::SetLedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::SetLedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::SetLedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa4782193d7ccea55ca2a5cf7f127ff5";
  }

  static const char* value(const ::my_msgs::SetLedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa4782193d7ccea5ULL;
  static const uint64_t static_value2 = 0x5ca2a5cf7f127ff5ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/SetLedRequest";
  }

  static const char* value(const ::my_msgs::SetLedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::SetLedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 lednum\n"
"bool state\n"
;
  }

  static const char* value(const ::my_msgs::SetLedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::SetLedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lednum);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::SetLedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::SetLedRequest_<ContainerAllocator>& v)
  {
    s << indent << "lednum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lednum);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_SETLEDREQUEST_H
