// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class simple_signalResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.waited_duration = null;
    }
    else {
      if (initObj.hasOwnProperty('waited_duration')) {
        this.waited_duration = initObj.waited_duration
      }
      else {
        this.waited_duration = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type simple_signalResult
    // Serialize message field [waited_duration]
    bufferOffset = _serializer.int64(obj.waited_duration, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type simple_signalResult
    let len;
    let data = new simple_signalResult(null);
    // Deserialize message field [waited_duration]
    data.waited_duration = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/simple_signalResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e61c59ff9e457607cf80eb990f19d4d3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    int64 waited_duration
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new simple_signalResult(null);
    if (msg.waited_duration !== undefined) {
      resolved.waited_duration = msg.waited_duration;
    }
    else {
      resolved.waited_duration = 0
    }

    return resolved;
    }
};

module.exports = simple_signalResult;
