// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class simple_signalGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.wait_duration = null;
      this.signal_number = null;
    }
    else {
      if (initObj.hasOwnProperty('wait_duration')) {
        this.wait_duration = initObj.wait_duration
      }
      else {
        this.wait_duration = 0.0;
      }
      if (initObj.hasOwnProperty('signal_number')) {
        this.signal_number = initObj.signal_number
      }
      else {
        this.signal_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type simple_signalGoal
    // Serialize message field [wait_duration]
    bufferOffset = _serializer.float64(obj.wait_duration, buffer, bufferOffset);
    // Serialize message field [signal_number]
    bufferOffset = _serializer.int64(obj.signal_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type simple_signalGoal
    let len;
    let data = new simple_signalGoal(null);
    // Deserialize message field [wait_duration]
    data.wait_duration = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [signal_number]
    data.signal_number = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/simple_signalGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a0a9e9d680822ae4c2e7427383594954';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    float64 wait_duration
    int64 signal_number
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new simple_signalGoal(null);
    if (msg.wait_duration !== undefined) {
      resolved.wait_duration = msg.wait_duration;
    }
    else {
      resolved.wait_duration = 0.0
    }

    if (msg.signal_number !== undefined) {
      resolved.signal_number = msg.signal_number;
    }
    else {
      resolved.signal_number = 0
    }

    return resolved;
    }
};

module.exports = simple_signalGoal;
