// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class num_actionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.bin_num = null;
    }
    else {
      if (initObj.hasOwnProperty('bin_num')) {
        this.bin_num = initObj.bin_num
      }
      else {
        this.bin_num = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type num_actionGoal
    // Serialize message field [bin_num]
    bufferOffset = _serializer.int64(obj.bin_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type num_actionGoal
    let len;
    let data = new num_actionGoal(null);
    // Deserialize message field [bin_num]
    data.bin_num = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/num_actionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1327ba78bb595c490506018fc2008a3e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    int64 bin_num
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new num_actionGoal(null);
    if (msg.bin_num !== undefined) {
      resolved.bin_num = msg.bin_num;
    }
    else {
      resolved.bin_num = 0
    }

    return resolved;
    }
};

module.exports = num_actionGoal;
