// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class num_actionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentage_done = null;
    }
    else {
      if (initObj.hasOwnProperty('percentage_done')) {
        this.percentage_done = initObj.percentage_done
      }
      else {
        this.percentage_done = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type num_actionFeedback
    // Serialize message field [percentage_done]
    bufferOffset = _serializer.float64(obj.percentage_done, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type num_actionFeedback
    let len;
    let data = new num_actionFeedback(null);
    // Deserialize message field [percentage_done]
    data.percentage_done = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/num_actionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e4296ebcdecd59873bb1d94db9895591';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float64 percentage_done
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new num_actionFeedback(null);
    if (msg.percentage_done !== undefined) {
      resolved.percentage_done = msg.percentage_done;
    }
    else {
      resolved.percentage_done = 0.0
    }

    return resolved;
    }
};

module.exports = num_actionFeedback;
