// Generated by gencpp from file my_robot_msgs/robot.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_ROBOT_H
#define MY_ROBOT_MSGS_MESSAGE_ROBOT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct robot_
{
  typedef robot_<ContainerAllocator> Type;

  robot_()
    : signal_number(0)
    , message()  {
    }
  robot_(const ContainerAllocator& _alloc)
    : signal_number(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _signal_number_type;
  _signal_number_type signal_number;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::my_robot_msgs::robot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::robot_<ContainerAllocator> const> ConstPtr;

}; // struct robot_

typedef ::my_robot_msgs::robot_<std::allocator<void> > robot;

typedef boost::shared_ptr< ::my_robot_msgs::robot > robotPtr;
typedef boost::shared_ptr< ::my_robot_msgs::robot const> robotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::robot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::robot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::robot_<ContainerAllocator1> & lhs, const ::my_robot_msgs::robot_<ContainerAllocator2> & rhs)
{
  return lhs.signal_number == rhs.signal_number &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::robot_<ContainerAllocator1> & lhs, const ::my_robot_msgs::robot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::robot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::robot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::robot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::robot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab597da5ada892a08fde55bf769237dd";
  }

  static const char* value(const ::my_robot_msgs::robot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab597da5ada892a0ULL;
  static const uint64_t static_value2 = 0x8fde55bf769237ddULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/robot";
  }

  static const char* value(const ::my_robot_msgs::robot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 signal_number\n"
"string message\n"
;
  }

  static const char* value(const ::my_robot_msgs::robot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::robot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal_number);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::robot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::robot_<ContainerAllocator>& v)
  {
    s << indent << "signal_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.signal_number);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_ROBOT_H
