// Generated by gencpp from file my_robot_msgs/signalRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SIGNALREQUEST_H
#define MY_ROBOT_MSGS_MESSAGE_SIGNALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct signalRequest_
{
  typedef signalRequest_<ContainerAllocator> Type;

  signalRequest_()
    : signal_number(0)  {
    }
  signalRequest_(const ContainerAllocator& _alloc)
    : signal_number(0)  {
  (void)_alloc;
    }



   typedef int64_t _signal_number_type;
  _signal_number_type signal_number;





  typedef boost::shared_ptr< ::my_robot_msgs::signalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::signalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct signalRequest_

typedef ::my_robot_msgs::signalRequest_<std::allocator<void> > signalRequest;

typedef boost::shared_ptr< ::my_robot_msgs::signalRequest > signalRequestPtr;
typedef boost::shared_ptr< ::my_robot_msgs::signalRequest const> signalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::signalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::signalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::signalRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::signalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.signal_number == rhs.signal_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::signalRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::signalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::signalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::signalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::signalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a36665241ea9676ae26d106d91ba47fd";
  }

  static const char* value(const ::my_robot_msgs::signalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa36665241ea9676aULL;
  static const uint64_t static_value2 = 0xe26d106d91ba47fdULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/signalRequest";
  }

  static const char* value(const ::my_robot_msgs::signalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 signal_number\n"
;
  }

  static const char* value(const ::my_robot_msgs::signalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::signalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::signalRequest_<ContainerAllocator>& v)
  {
    s << indent << "signal_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.signal_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SIGNALREQUEST_H
