// Generated by gencpp from file my_robot_msgs/signalResponse.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SIGNALRESPONSE_H
#define MY_ROBOT_MSGS_MESSAGE_SIGNALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct signalResponse_
{
  typedef signalResponse_<ContainerAllocator> Type;

  signalResponse_()
    : color()
    , message()  {
    }
  signalResponse_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::my_robot_msgs::signalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::signalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct signalResponse_

typedef ::my_robot_msgs::signalResponse_<std::allocator<void> > signalResponse;

typedef boost::shared_ptr< ::my_robot_msgs::signalResponse > signalResponsePtr;
typedef boost::shared_ptr< ::my_robot_msgs::signalResponse const> signalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::signalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::signalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::signalResponse_<ContainerAllocator1> & lhs, const ::my_robot_msgs::signalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::signalResponse_<ContainerAllocator1> & lhs, const ::my_robot_msgs::signalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::signalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::signalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::signalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4c3be35cd7d8d2dbd285480bb7150b6";
  }

  static const char* value(const ::my_robot_msgs::signalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4c3be35cd7d8d2dULL;
  static const uint64_t static_value2 = 0xbd285480bb7150b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/signalResponse";
  }

  static const char* value(const ::my_robot_msgs::signalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n"
"string message\n"
;
  }

  static const char* value(const ::my_robot_msgs::signalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::signalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::signalResponse_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SIGNALRESPONSE_H
